[tools]
node = "22.14.0"
python = "3.12.9"
uv = "latest"
moonrepo = "1.34.0"
bun = "latest"

[env]
MISE_PYTHON_UV_VENV_AUTO = true

[alias]
moonrepo = "asdf:https://github.com/asdf-community/asdf-moonrepo"
