# Generated by Django 4.2.20 on 2025-04-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('server_name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('ssh_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be.sshkey')),
            ],
        ),
    ]
