# Generated by Django 4.2.20 on 2025-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0003_role_userrole_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='site_name',
        ),
        migrations.AddField(
            model_name='permission',
            name='servers',
            field=models.ManyToManyField(to='be.server'),
        ),
    ]
