# Generated by Django 4.2.20 on 2025-04-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0004_remove_permission_server_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
