# Generated by Django 4.2.20 on 2025-04-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0006_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.AddField(
            model_name='userrole',
            name='roles',
            field=models.ManyToManyField(blank=True, to='be.role'),
        ),
    ]
