[installer]
    modern-installation = true
    parallel            = true
    no-binary           = false
    # max-workers = number_of_cores + 4

[solver]
    lazy-wheel = true

[virtualenvs]
    create               = true
    in-project           = true
    prompt               = "{project_name}"

[virtualenvs.options]
    always-copy          = false
    no-pip               = false
    no-setuptools        = false
    system-site-packages = false

[keyring]
    enabled = true

[warnings]
    export = false # https://github.com/python-poetry/poetry/pull/8562

[experimental]
    system-git-client = false
